---

- name: "ingress-rules"
  k8s:
    state: present
    definition:
      apiVersion: networking.k8s.io/v1beta1
      kind: Ingress
      metadata:
        name: "{{ basename }}-ingress-class-green"
        namespace: "{{ namespace }}"
        annotations:
          kubernetes.io/ingress.class: "class-green"
          nginx.ingress.kubernetes.io/ssl-redirect: "false"
          nginx.ingress.kubernetes.io/rewrite-target: /$2
      spec:
        rules:
        # Expose products-data service
        - host: "{{ ingress_host }}"
          http:
            paths:
            - path: "/{{ namespace }}/{{ basename }}-admin-api(/|$)(.*)"
              backend:
                serviceName: "{{ basename }}-admin-api"
                servicePort: 80
            - path: "/{{ namespace }}/{{ basename }}-content-api(/|$)(.*)"
              backend:
                serviceName: "{{ basename }}-content-api"
                servicePort: 80