
namespace: prod-web

ingress_host: service-k8s-p02.int.ellosgroup.com
version: v0.7.0
exclude_list:
-

content_api:
  port: 3000
  replicas: 1
  resources:
    requests:
      cpu: "500m"
      memory: "1Gi"

admin_api:
  port: 3000
  replicas: 1
  resources:
    requests:
      cpu: "500m"
      memory: "1Gi"

nfs_share:
  path: "/srv/nfs/k8s/prod02/opencms"
  server: "nfscl-01.rcndmz.ad"
  storage_size: "10Gi"
  name: "pvc-opencms"
