BEGIN TRY

BEGIN TRAN;

-- AlterTable
ALTER TABLE [dbo].[ContentBlockVariantVersion] ADD [slug] NVARCHAR(1000) NOT NULL CONSTRAINT [ContentBlockVariantVersion_slug_df] DEFAULT '';

COMMIT TRAN;

END TRY
BEGIN CATCH

IF @@TRANCOUNT > 0
BEGIN
    ROLLBACK TRAN;
END;
THROW

END CATCH
