---

- name: Create PersistentVolumeClaim
  k8s:
    state: present
    definition:
      kind: PersistentVolumeClaim
      apiVersion: v1
      metadata:
        name: "pvc-opencms"
        namespace: "{{ namespace }}"
      spec:
        accessModes:
          - ReadWriteMany
        volumeMode: Filesystem
        resources:
          requests:
            storage: "{{ nfs_share.storage_size }}"
        storageClassName: ""
        selector:
          matchLabels:
            app: "opencms-mirror"
