BEGIN TRY

BEGIN TRAN;

-- AlterTable
ALTER TABLE [dbo].[Page] ADD [pageId] NVARCHAR(1000);

-- AddForeignKey
ALTER TABLE [dbo].[Page] ADD CONSTRAINT [Page_pageId_fkey] FOREIGN KEY ([pageId]) REFERENCES [dbo].[Page]([id]) ON DELETE NO ACTION ON UPDATE NO ACTION;

COMMIT TRAN;

END TRY
BEGIN CATCH

IF @@TRANCOUNT > 0
BEGIN
    ROLLBACK TRAN;
END;
THROW

END CATCH
